export const GET_FOOD_REQUEST = "GET_FOOD_REQUEST"
export const GET_FOOD_SUCCESS = "GET_FOOD_SUCCESS"
export const GET_FOOD_FAIL = "GET_FOOD_FAIL" 

export const GET_ALL_FOOD_REQUEST = "GET_ALL_FOOD_REQUEST"
export const GET_ALL_FOOD_SUCCESS = "GET_ALL_FOOD_SUCCESS"
export const GET_ALL_FOOD_FAIL = "GET_ALL_FOOD_FAIL" 

export const CREATE_FOOD_REQUEST = "CREATE_FOOD_REQUEST"
export const CREATE_FOOD_SUCCESS = "CREATE_FOOD_SUCCESS"
export const CREATE_FOOD_FAIL = "CREATE_FOOD_FAIL" 

