export const LOGIN_WITH_PHONE_REQUEST = "LOGIN_WITH_PHONE_REQUEST"
export const LOGIN_WITH_PHONE_SUCCESS = "LOGIN_WITH_PHONE_SUCCESS"
export const LOGIN_WITH_PHONE_FAIL = "LOGIN_WITH_PHONE_FAIL"


export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST"
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL"



export const ADMIN_SIGNUP_REQUEST = "ADMIN_SIGNUP_REQUEST"
export const ADMIN_SIGNUP_SUCCESS = "ADMIN_SIGNUP_SUCCESS"
export const ADMIN_SIGNUP_FAIL = "ADMIN_SIGNUP_FAIL"