

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL" 

export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST"
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS"
export const GET_ALL_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL" 

export const GET_PRODUCTS_BY_CATEGORY_REQUEST = "GET_PRODUCTS_BY_CATEGORY_REQUEST"
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS = "GET_PRODUCTS_BY_CATEGORY_SUCCESS"
export const GET_PRODUCTS_BY_CATEGORY_FAIL = "GET_PRODUCTS_BY_CATEGORY_FAIL" 

export const GET_PRODUCTS_BY_SEARCH_REQUEST = "GET_PRODUCTS_BY_SEARCH_REQUEST"
export const GET_PRODUCTS_BY_SEARCH_SUCCESS = "GET_PRODUCTS_BY_SEARCH_SUCCESS"
export const GET_PRODUCTS_BY_SEARCH_FAIL = "GET_PRODUCTS_BY_SEARCH_FAIL" 

//get top 5 product constants
export const GET_TOP_FIVE_PRODUCTS_REQUEST = "GET_TOP_FIVE_PRODUCTS_REQUEST"
export const GET_TOP_FIVE_PRODUCTS_SUCCESS = "GET_TOP_FIVE_PRODUCTS_SUCCESS"
export const GET_TOP_FIVE_PRODUCTS_FAIL = "GET_TOP_FIVE_PRODUCTS_FAIL" 



export const CREATE_PRODUCTS_REQUEST = "CREATE_PRODUCTS_REQUEST"
export const CREATE_PRODUCTS_SUCCESS = "CREATE_PRODUCTS_SUCCESS"
export const CREATE_PRODUCTS_FAIL = "CREATE_PRODUCTS_FAIL" 


export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST"
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS"
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL" 
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET" 


export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST"
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS"
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL"


export const PRODUCT_EDIT_REQUEST = "PRODUCT_EDIT_REQUEST"
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS"
export const PRODUCT_EDIT_FIAL = "PRODUCT_EDIT_FIAL"


export const RECORD_PRODUCT_SEARCH_REQUEST = "RECORD_PRODUCT_SEARCH_REQUEST"
export const RECORD_PRODUCT_SEARCH_SUCCESS = "RECORD_PRODUCT_SEARCH_SUCCESS"
export const RECORD_PRODUCT_SEARCH_FAIL = "RECORD_PRODUCT_SEARCH_FAIL"


export const RECORD_PRODUCT_VISIT_REQUEST = "RECORD_PRODUCT_VISIT_REQUEST"
export const RECORD_PRODUCT_VISIT_SUCCESS = "RECORD_PRODUCT_VISIT_SUCCESS"
export const RECORD_PRODUCT_VISIT_FAIL = "RECORD_PRODUCT_VISIT_FAIL"


export const COMMENTING_REQUEST = "COMMENTING_REQUEST";
export const COMMENTING_SUCCESS = "COMMENTING_SUCCESS";
export const COMMENTING_FAIL = "COMMENTING_FAIL";


export const FETCH_COMMENT_REQUEST = "FETCH_COMMENT_REQUEST";
export const FETCH_COMMENT_SUCCESS = "FETCH_COMMENT_SUCCESS";
export const FETCH_COMMENT_FAIL = "FETCH_COMMENT_FAIL";

//to sell products
export const SELL_PRODUCT_REQUEST = "SELL_PRODUCT_REQUEST"
export const SELL_PRODUCT_SUCCESS = "SELL_PRODUCT_SUCCESS"
export const SELL_PRODUCT_FAIL = "SELL_PRODUCT_FAIL"

//return sold product

export const RETURN_PRODUCT_REQUEST = "RETURN_PRODUCT_REQUEST"
export const RETURN_PRODUCT_SUCCESS = "RETURN_PRODUCT_SUCCESS"
export const RETURN_PRODUCT_FAIL = "RETURN_PRODUCT_FAIL"
