export const GET_RESTAURANT_REQUEST = "GET_RESTAURANT_REQUEST"
export const GET_RESTAURANT_SUCCESS = "GET_RESTAURANT_SUCCESS"
export const GET_RESTAURANT_FAIL = "GET_RESTAURANT_FAIL" 

export const GET_ALL_RESTAURANTS_REQUEST = "GET_ALL_RESTAURANTS_REQUEST"
export const GET_ALL_RESTAURANTS_SUCCESS = "GET_ALL_RESTAURANTS_SUCCESS"
export const GET_ALL_RESTAURANTS_FAIL = "GET_ALL_RESTAURANTS_FAIL" 

export const CREATE_RESTAURANT_REQUEST = "CREATE_RESTAURANT_REQUEST"
export const CREATE_RESTAURANT_SUCCESS = "CREATE_RESTAURANT_SUCCESS"
export const CREATE_RESTAURANT_FAIL = "CREATE_RESTAURANT_FAIL" 

